### ISSUE TITLE
How to update image?

### ISSUE THREAD

**Issue by Venegrad** [LuXDAmore/vue-fake3d-image-effect#14]
I have two themes with different images, how i can can update event for change image inside?

**Comment by LuXDAmore** [comment]
Hello @Venegrad 

Can you reproduce the issue?

Also, you can try to simply use the `key` attribute [in the component](https://vuejs.org/api/built-in-special-attributes.html#key).

For example:

```html

    <component :key="DATA_THAT_CHANGE" :image="DATA_THAT_CHANGE" />

```

Or with vIf directive:

```html

    <component v-if="CONDITION" image="IMAGE_1" />
    <component v-else image="IMAGE_2" />

```

Hope this helps.
